name: nanolink_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  dotenv: ^4.0.1
  nanolink_core:
    path: ../nanolink_core
  shortid: ^0.1.2
  supabase: ^0.3.6
  tuple: ^2.0.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
