include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.config.dart
